Support Orature file upload
Bible-Translation-Tools/maui pull request #44
Opened 2021-02-03 19:24 UTC by AnonymousWalker

2021-02-03 21:30 UTC, jsarabia reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[build.gradle, line 69 at r4](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MSdaGvZ4yIynOVhGsWh:-MSdaGv_3jubWoZMhvlr:b-kyrnwk) ([raw file](https://github.com/bible-translation-tools/maui/blob/b6d3fa98cab0b658ad4d87eaad93fae6c0542dfd/build.gradle#L69)):*
> ```Gradle
>     compileKotlin {
>         kotlinOptions.jvmTarget = "11"
>         kotlinOptions.allWarningsAsErrors = false
> ```

if there were no warnings previously, it seems reasonable to not let warnings in, not to just turn this off
___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 17 at r4](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MSdac7EEJ6Q2oTyDy57:-MSdac7EEJ6Q2oTyDy58:b-4pvnbw) ([raw file](https://github.com/bible-translation-tools/maui/blob/b6d3fa98cab0b658ad4d87eaad93fae6c0542dfd/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L17)):*
> ```Kotlin
>  *  @throws IOException if the file passed into constructor is not from Orature
>  */
> class ProcessOratureFile(file: File) {
> ```

Please use the kotlin-resource-container library rather than creating another resource container library. Then, if changes are made to the RC spec, library, etc, we don't have to search through every app we have using resource containers and fix their implementations; we instead just import the newest library.

Additionally, this is a class in the use case package. The name sounds appropriate for a use case, but the functionality does not; I would expect the functionality to make use of the RC library to "process" it in whatever way is appropriate for this specific application and "use case"

The code however implies this to be a mini de-serialization library for reading from resource containers.


<!-- Sent from Reviewable.io -->

2021-02-04 11:48 UTC, mXaln requested changes
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker)

___
*[jvm/src/main/kotlin/org/bibletranslationtools/jvm/ui/main/MainViewModel.kt, line 111 at r5](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MSgqbO57H6JgtimxoMo:-MSgqbO57H6JgtimxoMp:b-kplasx) ([raw file](https://github.com/bible-translation-tools/maui/blob/2cfedb702d1357af50ed561f76cc7a5b3e22c97a/jvm/src/main/kotlin/org/bibletranslationtools/jvm/ui/main/MainViewModel.kt#L111)):*
> ```Kotlin
>         val filesToImport = mutableListOf<File>()
>         files.forEach { file ->
>             if (ProcessOratureFile.isOratureFormat(file)) {
> ```

At this level of iteration, file can be a directory. If for example you drop a directory with orature zip files. Thus an exception will be thrown. You need to move your if/else code inside the filtered iteration (`filter { it.isFile}.forEach...` )


<!-- Sent from Reviewable.io -->

2021-02-04 13:55 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @mXaln)

___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 17 at r4](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MSdac7EEJ6Q2oTyDy57:-MShI15H3Zx9B5aA6MQw:b-7ytkdv) ([raw file](https://github.com/bible-translation-tools/maui/blob/b6d3fa98cab0b658ad4d87eaad93fae6c0542dfd/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L17)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Please use the kotlin-resource-container library rather than creating another resource container library. Then, if changes are made to the RC spec, library, etc, we don't have to search through every app we have using resource containers and fix their implementations; we instead just import the newest library.

Additionally, this is a class in the use case package. The name sounds appropriate for a use case, but the functionality does not; I would expect the functionality to make use of the RC library to "process" it in whatever way is appropriate for this specific application and "use case"

The code however implies this to be a mini de-serialization library for reading from resource containers.
</blockquote></details>

Yes I replaced that with kotlin rc library. I was undecided between picking up the library or using a simple deserializer, now I'm aware that there's a huge benefit in a library (although it may be more than what we need).
___
*[jvm/src/main/kotlin/org/bibletranslationtools/jvm/ui/main/MainViewModel.kt, line 111 at r5](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MSgqbO57H6JgtimxoMo:-MShJb0a2EuQEmZjYbUh:bx5ia6u) ([raw file](https://github.com/bible-translation-tools/maui/blob/2cfedb702d1357af50ed561f76cc7a5b3e22c97a/jvm/src/main/kotlin/org/bibletranslationtools/jvm/ui/main/MainViewModel.kt#L111)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

At this level of iteration, file can be a directory. If for example you drop a directory with orature zip files. Thus an exception will be thrown. You need to move your if/else code inside the filtered iteration (`filter { it.isFile}.forEach...` )
</blockquote></details>

thanks for the good catch, I got the changes up


<!-- Sent from Reviewable.io -->

2021-02-04 14:14 UTC, mXaln requested changes
> Reviewed 3 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @mXaln)

___
*[jvm/src/main/kotlin/org/bibletranslationtools/jvm/ui/main/MainViewModel.kt, line 111 at r6](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MShNsF8EpGl_IX8Qdr7:-MShNsF96zkAI4a2LrSV:b-npmqpo) ([raw file](https://github.com/bible-translation-tools/maui/blob/f3735ca66061b186c9e952235ec7de621181cce4/jvm/src/main/kotlin/org/bibletranslationtools/jvm/ui/main/MainViewModel.kt#L111)):*
> ```Kotlin
>         val filesToImport = mutableListOf<File>()
>         files.forEach { file ->
>             file.walk().filter { it.isFile }.forEach { fileNode ->
> ```

I wouldn't call it a fileNode. If you want to name it, call the top one fileOrDir, and this one just file


<!-- Sent from Reviewable.io -->

2021-02-04 14:21 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/src/main/kotlin/org/bibletranslationtools/jvm/ui/main/MainViewModel.kt, line 111 at r6](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MShNsF8EpGl_IX8Qdr7:-MShOYol08TS5s4-2RGT:b-896fix) ([raw file](https://github.com/bible-translation-tools/maui/blob/f3735ca66061b186c9e952235ec7de621181cce4/jvm/src/main/kotlin/org/bibletranslationtools/jvm/ui/main/MainViewModel.kt#L111)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

I wouldn't call it a fileNode. If you want to name it, call the top one fileOrDir, and this one just file
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-04 15:11 UTC, mXaln requested changes
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @mXaln)

___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 30 at r8](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MSh_pM16R9YYhRAgxKS:-MSh_pM16R9YYhRAgxKT:b10ow9w) ([raw file](https://github.com/bible-translation-tools/maui/blob/16a96b51f1ced2e85e7b2b29cb616d98314f7336/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L30)):*
> ```Kotlin
>         zipFile.use {
>             it.entries().iterator().forEach { entry ->
>                 if (
> ```

this looks like a not good line break. You could take out the expression and assign it to variable.
```
val isWav = File(entry.name).extension == MediaExtension.WAV.toString()
if (entry.name.startsWith("content") && isWav) {
    extractEntry(entry, tempDir)
}
```


<!-- Sent from Reviewable.io -->

2021-02-04 15:12 UTC, mXaln reviewed
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: all files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)



<!-- Sent from Reviewable.io -->

2021-02-04 15:14 UTC, AnonymousWalker commented
___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 30 at r8](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MSh_pM16R9YYhRAgxKS:-MShapEJ0OI-PkHMjU_u:b-toumwg) ([raw file](https://github.com/bible-translation-tools/maui/blob/16a96b51f1ced2e85e7b2b29cb616d98314f7336/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L30)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

this looks like a not good line break. You could take out the expression and assign it to variable.
```
val isWav = File(entry.name).extension == MediaExtension.WAV.toString()
if (entry.name.startsWith("content") && isWav) {
    extractEntry(entry, tempDir)
}
```
</blockquote></details>

yeah that looks great


<!-- Sent from Reviewable.io -->

2021-02-04 15:26 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @mXaln)

___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 23 at r9](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MShcg5f8jwIYsYvcMhF:-MShcg5f8jwIYsYvcMhG:byzo6bk) ([raw file](https://github.com/bible-translation-tools/maui/blob/63fcd51ef6379f8ef4fcef320ea5b2bcaaab6b42/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L23)):*
> ```Kotlin
>      * Regard Orature resource container for more detail
>      */
>     fun extractAudio(): List<File> {
> ```

The resource container library provides functionality for accessing the files within them.

Who's responsibility should it be to know and understand where to look around for files within a resource container? Maui, the RC library, or both?

Also tagging @mxaln for the purpose of him joining in on the discussion of architectural philosophy


<!-- Sent from Reviewable.io -->

2021-02-04 18:16 UTC, mXaln reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: all files reviewed, 3 unresolved discussions (waiting on @jsarabia)

___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 23 at r9](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MShcg5f8jwIYsYvcMhF:-MSiFBhm7WPD6-ZNvvud:b-z9qxeh) ([raw file](https://github.com/bible-translation-tools/maui/blob/63fcd51ef6379f8ef4fcef320ea5b2bcaaab6b42/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L23)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

The resource container library provides functionality for accessing the files within them.

Who's responsibility should it be to know and understand where to look around for files within a resource container? Maui, the RC library, or both?

Also tagging @mxaln for the purpose of him joining in on the discussion of architectural philosophy
</blockquote></details>

Since we are using RC to validate orature file, then I think it would be reasonable to use it to provide the list of files to import, if it has that feature.


<!-- Sent from Reviewable.io -->

2021-02-15 13:30 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 9 at r12](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MT_rN5VDZpzeacyVnTt:-MT_rN5VDZpzeacyVnTu:b-1avn3) ([raw file](https://github.com/bible-translation-tools/maui/blob/09cae42e57ce22327575a3d27423fc0bc9e6a865/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L9)):*
> ```Kotlin
> class ProcessOratureFile(private val file: File) {
> 
>     fun extractAudio(): List<File> {
> ```

any exceptions here? What should happen if there are?
___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 13 at r12](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MT_rjxk5EQJ0INAdTBC:-MT_rjxk5EQJ0INAdTBD:bxpcp3a) ([raw file](https://github.com/bible-translation-tools/maui/blob/09cae42e57ce22327575a3d27423fc0bc9e6a865/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L13)):*
> ```Kotlin
> 
>         ResourceContainer.load(file).use { rc ->
>             val content = rc.getProjectContent(extension=MediaExtension.WAV.toString())
> ```

Should the wav extension be a parameter for extract audio?
___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 34 at r12](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MT_r8UN31fsPqpTdAU9:-MT_r8UO7fIpMPySHzt9:b2sffce) ([raw file](https://github.com/bible-translation-tools/maui/blob/09cae42e57ce22327575a3d27423fc0bc9e6a865/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L34)):*
> ```Kotlin
> 
>     companion object {
>         fun isOratureFormat(file: File): Boolean = file.extension == "zip"
> ```

Why not use your validate orature file use case here?


<!-- Sent from Reviewable.io -->

2021-02-15 13:46 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @mXaln)

___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 13 at r12](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MT_rjxk5EQJ0INAdTBC:-MT_w-hKC40VgQCr248E:b5acyq0) ([raw file](https://github.com/bible-translation-tools/maui/blob/09cae42e57ce22327575a3d27423fc0bc9e6a865/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L13)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Should the wav extension be a parameter for extract audio?
</blockquote></details>

I would make it as a class property, since it's kindof narrow within this particular use case
___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 34 at r12](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MT_r8UN31fsPqpTdAU9:-MT_uvIi6EPz9vc2We-a:b8r9arg) ([raw file](https://github.com/bible-translation-tools/maui/blob/09cae42e57ce22327575a3d27423fc0bc9e6a865/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L34)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Why not use your validate orature file use case here?
</blockquote></details>

This method would be more appropriate to be called when iterating over the imported files in MainViewModel, as I did not expect to try validating (valid Orature file or not?) every single file we imported... 


<!-- Sent from Reviewable.io -->

2021-02-15 13:52 UTC, AnonymousWalker commented
___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 34 at r12](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MT_r8UN31fsPqpTdAU9:-MT_xEMRDczh6I6-MVbe:b-dfvec) ([raw file](https://github.com/bible-translation-tools/maui/blob/09cae42e57ce22327575a3d27423fc0bc9e6a865/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L34)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

This method would be more appropriate to be called when iterating over the imported files in MainViewModel, as I did not expect to try validating (valid Orature file or not?) every single file we imported... 
</blockquote></details>

I separated the validate() for only if there is an Orature-like file


<!-- Sent from Reviewable.io -->

2021-02-15 14:18 UTC, AnonymousWalker commented
___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 9 at r12](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MT_rN5VDZpzeacyVnTt:-MTa2ceV1YB4L1hgEbNC:bl8rhe5) ([raw file](https://github.com/bible-translation-tools/maui/blob/09cae42e57ce22327575a3d27423fc0bc9e6a865/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L9)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

any exceptions here? What should happen if there are?
</blockquote></details>

yep I added @Throws for it


<!-- Sent from Reviewable.io -->

2021-02-15 14:27 UTC, mXaln requested changes
> Reviewed 4 of 6 files at r11, 3 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: all files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @throws)

___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 13 at r12](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MT_rjxk5EQJ0INAdTBC:-MTa3FXt9w6hfwVIvnT3:bnc6v98) ([raw file](https://github.com/bible-translation-tools/maui/blob/09cae42e57ce22327575a3d27423fc0bc9e6a865/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L13)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

I would make it as a class property, since it's kindof narrow within this particular use case
</blockquote></details>

+ to move it up as the function argument
___
*[jvm/src/main/kotlin/org/bibletranslationtools/jvm/ui/main/MainViewModel.kt, line 113 at r13](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MTa3l1E14X6PX5xPMdA:-MTa3l1E14X6PX5xPMdB:b-laq53k) ([raw file](https://github.com/bible-translation-tools/maui/blob/ea3cc86248fb163dc1a2c35679b8b06f0e29e3f4/jvm/src/main/kotlin/org/bibletranslationtools/jvm/ui/main/MainViewModel.kt#L113)):*
> ```Kotlin
>         files.forEach { fileOrDir ->
>             fileOrDir.walk().filter { it.isFile }.forEach { file ->
>                 if (ProcessOratureFile.isOratureFormat(file)) {
> ```

Since `isOratureFormat` is only checking if it's a zip file, then I would get rid of that companion object function and use file extension check here
```
if (file.extension == "zip") {
    filesToImport.addAll(processOratureFile(file))
}
```


<!-- Sent from Reviewable.io -->

2021-02-15 14:40 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: all files reviewed, 4 unresolved discussions (waiting on @jsarabia, @mXaln, and @throws)

___
*[jvm/src/main/kotlin/org/bibletranslationtools/jvm/ui/main/MainViewModel.kt, line 113 at r13](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MTa3l1E14X6PX5xPMdA:-MTa7FrQ9bAMiTA3f0HT:b-q9gf4a) ([raw file](https://github.com/bible-translation-tools/maui/blob/ea3cc86248fb163dc1a2c35679b8b06f0e29e3f4/jvm/src/main/kotlin/org/bibletranslationtools/jvm/ui/main/MainViewModel.kt#L113)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Since `isOratureFormat` is only checking if it's a zip file, then I would get rid of that companion object function and use file extension check here
```
if (file.extension == "zip") {
    filesToImport.addAll(processOratureFile(file))
}
```
</blockquote></details>

So if Orature supports another file type, saying .tar, would that mean we add another condition == "tar" ? I was using that static method in case of such issue, unless it's not necessary


<!-- Sent from Reviewable.io -->

2021-02-15 14:45 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @jsarabia, @mXaln, and @throws)

___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 13 at r12](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MT_rjxk5EQJ0INAdTBC:-MTa86DO7eXZnN_YLra1:b-pkgs1b) ([raw file](https://github.com/bible-translation-tools/maui/blob/09cae42e57ce22327575a3d27423fc0bc9e6a865/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L13)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

+ to move it up as the function argument
</blockquote></details>

Sounds good to me


<!-- Sent from Reviewable.io -->

2021-02-15 14:56 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker, @mXaln, and @throws)

___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 9 at r12](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MT_rN5VDZpzeacyVnTt:-MTa9kWT0f6MecNQEQqP:b-fkgmrw) ([raw file](https://github.com/bible-translation-tools/maui/blob/09cae42e57ce22327575a3d27423fc0bc9e6a865/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L9)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

yep I added @Throws for it
</blockquote></details>

Never throw "Exception;" try to think about what kind or kinds of exceptions you could have and whether you should handle them here or not.

This annotation says to me as a potential user of this public method 
"some stuff could break  ¯\_(ツ)_/¯ idk"
___
*[common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt, line 34 at r12](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MT_r8UN31fsPqpTdAU9:-MTaAECc0Nfkk6HDQZSq:b-qa157) ([raw file](https://github.com/bible-translation-tools/maui/blob/09cae42e57ce22327575a3d27423fc0bc9e6a865/common/src/main/kotlin/org/bibletranslationtools/common/usecases/ProcessOratureFile.kt#L34)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

I separated the validate() for only if there is an Orature-like file
</blockquote></details>

Yeah but like, checking if the format is correct is fundamentally verification code. If nothing else, I expect to locate this method in that source file, not here, but furthermore, again, a zip could be a valid file extension for something that isn't of Orature format, and we want to let it get processed by its appropriate processor; not get eaten by this one.

I know you should be handling "well, we tried but it wasn't handled by this processor" in which it tries the next (and if you're not, well, you should), but there's also some degree of, at what level should we find out or check for certain information- it's like cooking a recipe before checking to see if we actually had all the ingredients yet.


<!-- Sent from Reviewable.io -->

2021-02-15 18:31 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker, @mXaln, and @throws)

___
*[common/src/main/kotlin/org/bibletranslationtools/common/validators/OratureValidator.kt, line 14 at r15](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MTasVC-EQN8L4yTzclC:-MTasVC-EQN8L4yTzclD:bwewtqn) ([raw file](https://github.com/bible-translation-tools/maui/blob/d41711e4b931791d41b931cb237208d06bfb364f/common/src/main/kotlin/org/bibletranslationtools/common/validators/OratureValidator.kt#L14)):*
> ```Kotlin
>             ResourceContainer.load(file).use {
>                 if (it.manifest.dublinCore.creator != creatorName) {
>                     throw Exception()
> ```

why are you using an exception as a return value?
___
*[common/src/main/kotlin/org/bibletranslationtools/common/validators/OratureValidator.kt, line 18 at r15](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MTasd0kAbgpH-jfwKen:-MTasd0kAbgpH-jfwKeo:bimb3sf) ([raw file](https://github.com/bible-translation-tools/maui/blob/d41711e4b931791d41b931cb237208d06bfb364f/common/src/main/kotlin/org/bibletranslationtools/common/validators/OratureValidator.kt#L18)):*
> ```Kotlin
>             }
>         } catch (ex: Exception) {
>             throw Exception("Invalid Orature file")
> ```

This gets picked up by a logger. 
Log says:
"Invalid Orature File"

...is that useful for tracking down what caused the issue?


<!-- Sent from Reviewable.io -->

2021-02-16 15:42 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 3 of 9 files reviewed, 4 unresolved discussions (waiting on @jsarabia, @mXaln, and @throws)

___
*[common/src/main/kotlin/org/bibletranslationtools/common/validators/OratureValidator.kt, line 14 at r15](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MTasVC-EQN8L4yTzclC:-MTfQ4GX13qZ2ZVzX4PU:b-896fix) ([raw file](https://github.com/bible-translation-tools/maui/blob/d41711e4b931791d41b931cb237208d06bfb364f/common/src/main/kotlin/org/bibletranslationtools/common/validators/OratureValidator.kt#L14)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why are you using an exception as a return value?
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/bibletranslationtools/common/validators/OratureValidator.kt, line 18 at r15](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MTasd0kAbgpH-jfwKen:-MTfVSCQ8UejeCLZGNIw:b-896fix) ([raw file](https://github.com/bible-translation-tools/maui/blob/d41711e4b931791d41b931cb237208d06bfb364f/common/src/main/kotlin/org/bibletranslationtools/common/validators/OratureValidator.kt#L18)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This gets picked up by a logger. 
Log says:
"Invalid Orature File"

...is that useful for tracking down what caused the issue?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-22 20:54 UTC, AnonymousWalker commented on common/src/main/kotlin/org/bibletranslationtools/maui/common/usecases/ParseFileName.kt
> +    fun read(): FileData {
this will replace parse(): Single<FileData>
I'm working on updating the related code usage of this

2021-02-23 16:27 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 3 of 26 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[common/src/main/kotlin/org/bibletranslationtools/maui/common/usecases/FileProcessingRouter.kt, line 29 at r19](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MUEgjIA9XHSIw0MvXrb:-MUEgjIA9XHSIw0MvXrc:b-m0b7ko) ([raw file](https://github.com/bible-translation-tools/maui/blob/c1a4bb758ee432ab304c08d89d478ab53b1d5082/common/src/main/kotlin/org/bibletranslationtools/maui/common/usecases/FileProcessingRouter.kt#L29)):*
> ```Kotlin
>         processors.forEach {
>             val status = it.process(file, fileQueue, resultList)
>             if (status == FileStatus.PROCESSED) return
> ```

please add { } here


<!-- Sent from Reviewable.io -->

2021-02-23 18:32 UTC, jsarabia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44#-:-MUF9WPj7X236bNFEGRi:bnfp4nl)* status: 3 of 26 files reviewed, 2 unresolved discussions (waiting on @mXaln)



<!-- Sent from Reviewable.io -->

2021-02-24 13:40 UTC, mXaln requested changes
> Reviewed 1 of 4 files at r13, 12 of 18 files at r16, 10 of 10 files at r18, 4 of 4 files at r20, 1 of 1 files at r21.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: all files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker)

___
*[jvm/src/main/kotlin/org/bibletranslationtools/jvm/ui/main/MainViewModel.kt, line 113 at r13](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MTa3l1E14X6PX5xPMdA:-MTaP4IK4QwRFm4HVJli:bss3lx8) ([raw file](https://github.com/bible-translation-tools/maui/blob/ea3cc86248fb163dc1a2c35679b8b06f0e29e3f4/jvm/src/main/kotlin/org/bibletranslationtools/jvm/ui/main/MainViewModel.kt#L113)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

So if Orature supports another file type, saying .tar, would that mean we add another condition == "tar" ? I was using that static method in case of such issue, unless it's not necessary
</blockquote></details>

I'm not sure if Orature file will be a .tar ever. But we could add support for BTT Recorder zip files and those are different than Orature files
___
*[jvm/src/main/kotlin/org/bibletranslationtools/maui/jvm/ui/main/MainViewModel.kt, line 12 at r21](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MUJBsHo46mtws8WEHX9:-MUJBsHo46mtws8WEHXA:b-xo6tnw) ([raw file](https://github.com/bible-translation-tools/maui/blob/2750487078ee126a1a699aebcd6a199d72f21510/jvm/src/main/kotlin/org/bibletranslationtools/maui/jvm/ui/main/MainViewModel.kt#L12)):*
> ```Kotlin
> import javafx.scene.control.Alert
> import org.bibletranslationtools.maui.common.audio.BttrChunk
> import org.bibletranslationtools.maui.common.data.*
> ```

Please, don't use wildcard imports
___
*[jvm/src/main/kotlin/org/bibletranslationtools/maui/jvm/ui/main/MainViewModel.kt, line 16 at r21](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MUJBwf05NCp-VEtN8Yj:-MUJBwf05NCp-VEtN8Yk:bb4b7qj) ([raw file](https://github.com/bible-translation-tools/maui/blob/2750487078ee126a1a699aebcd6a199d72f21510/jvm/src/main/kotlin/org/bibletranslationtools/maui/jvm/ui/main/MainViewModel.kt#L16)):*
> ```Kotlin
> import org.bibletranslationtools.maui.common.fileprocessor.OratureFileProcessor
> import org.bibletranslationtools.maui.common.fileprocessor.WavProcessor
> import org.bibletranslationtools.maui.common.usecases.*
> ```

Same here, use separate import for every usecase


<!-- Sent from Reviewable.io -->

2021-02-24 13:49 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: 27 of 28 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[common/src/main/kotlin/org/bibletranslationtools/maui/common/usecases/FileProcessingRouter.kt, line 29 at r19](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MUEgjIA9XHSIw0MvXrb:-MUF50QN3jmhbe6FHVvS:b-896fix) ([raw file](https://github.com/bible-translation-tools/maui/blob/c1a4bb758ee432ab304c08d89d478ab53b1d5082/common/src/main/kotlin/org/bibletranslationtools/maui/common/usecases/FileProcessingRouter.kt#L29)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

please add { } here
</blockquote></details>

Done.
___
*[jvm/src/main/kotlin/org/bibletranslationtools/maui/jvm/ui/main/MainViewModel.kt, line 12 at r21](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MUJBsHo46mtws8WEHX9:-MUJHg9D3GYjp0Gsq4NG:b-896fix) ([raw file](https://github.com/bible-translation-tools/maui/blob/2750487078ee126a1a699aebcd6a199d72f21510/jvm/src/main/kotlin/org/bibletranslationtools/maui/jvm/ui/main/MainViewModel.kt#L12)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Please, don't use wildcard imports
</blockquote></details>

Done.
___
*[jvm/src/main/kotlin/org/bibletranslationtools/maui/jvm/ui/main/MainViewModel.kt, line 16 at r21](https://reviewable.io/reviews/bible-translation-tools/maui/44#-MUJBwf05NCp-VEtN8Yj:-MUJHfzt87HLRRsbvUHn:b-896fix) ([raw file](https://github.com/bible-translation-tools/maui/blob/2750487078ee126a1a699aebcd6a199d72f21510/jvm/src/main/kotlin/org/bibletranslationtools/maui/jvm/ui/main/MainViewModel.kt#L16)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Same here, use separate import for every usecase
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-24 13:51 UTC, mXaln approved these changes
> Reviewed 1 of 1 files at r22.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/44)* status: all files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker)



<!-- Sent from Reviewable.io -->

2021-02-24 13:55 UTC, merged