Allow to enter custom values (some filtered)
Bible-Translation-Tools/maui pull request #60
Opened 2023-06-15 13:12 UTC by mXaln

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Bible-Translation-Tools/maui/60)

2023-06-27 14:10 UTC, AnonymousWalker requested changes

2023-06-27 14:10 UTC, AnonymousWalker commented on common/src/main/kotlin/org/bibletranslationtools/maui/common/io/IReader.kt
> +interface IReader {
I would recommend a different name for this interface. Reader sounds a bit too general and also used by java I/O APIs. "IResourceReader", "ISchemaParser" or "IResourceParser" maybe a better name for it

2023-06-28 08:19 UTC, mXaln reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/maui/60)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/bibletranslationtools/maui/common/io/IReader.kt` line 5 at r6](https://reviewable.io/reviews/Bible-Translation-Tools/maui/60#gh-1243814879:-NZ03yhS4rPk3KdFXa-b:bmwe3ii) ([raw file](https://github.com/Bible-Translation-Tools/maui/blob/d87a6b9af38c6bfeda26d43613caa2ac34dcef0e/common/src/main/kotlin/org/bibletranslationtools/maui/common/io/IReader.kt#L5)):*
<details><summary><i>Previously, AnonymousWalker (Tony Tran) wrote…</i></summary><blockquote>

I would recommend a different name for this interface. Reader sounds a bit too general and also used by java I/O APIs. "IResourceReader", "ISchemaParser" or "IResourceParser" maybe a better name for it
</blockquote></details>

Sound good to me. Done.


<!-- Sent from Reviewable.io -->

2023-06-28 13:42 UTC, AnonymousWalker approved these changes

2023-06-28 13:54 UTC, merged